In [ ]:
import numpy as np
from scipy import spatial
import matplotlib.pyplot as plt
# from sklearn.manifold import TSNE
import nltk
from nltk.corpus import wordnet as wn
from functools import reduce
from collections import OrderedDict
from itertools import permutations, combinations, chain
import time
import re
import nltk
from nltk.corpus import wordnet
from google.colab import drive
import pandas as pd 
import gensim


from gensim.models import Word2Vec
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
!pip install openai

In [ ]:
dfAttributes=pd.read_csv('gdrive/My Drive/NIER-ICSE/data/test/attributes.csv')
dfAttributes['Results2_partialDiagram']=dfAttributes['Results2_partialDiagram'].apply(lambda x: x.split(','))
dfAttributes['attributes']=dfAttributes['attributes'].apply(lambda x: eval(x))
dfAttributes.fillna("",inplace=True)
dfAttributes['manualResults']=dfAttributes['manualResults'].apply(lambda x: x.split(','))
#dfAttributes['manualResults'][155]=[' name',' surname', ' nextDestination', ' phoneNumber', ' nextDestination', 'email']

In [ ]:
def removeEmptyString(listString):
  for idx,i in enumerate(listString): 
    if i=="": 
      listString.remove(i)
  return listString
dfAttributes['manualResults']=dfAttributes['manualResults'].apply(lambda x: removeEmptyString(x))

In [ ]:
def Recall(predictedList,GroundTruthList): #TP+/FN+TP 
  score=0  
  
  GroundTruthList=list(map(str.lower,GroundTruthList))
  for i in predictedList: 
    i=i.strip()
    if i.lower() in GroundTruthList : 
     
      score=score+1
  x=len(GroundTruthList)
  if x==0 : 
      return 0
  return score/len(GroundTruthList)

In [ ]:
dfAttributes['Exact_recall']=dfAttributes.apply(lambda x: Recall(x['Results2_partialDiagram'],(x['attributes']) ),axis=1)
#dfAttributes['precision']=dfAttributes.apply(lambda x: precision(x['Results2_partialDiagram'],(x['attributes']) ),axis=1)

In [ ]:
dfAttributes['Similar_recall']=dfAttributes.apply(lambda x: len((x['manualResults']) )/len(x['attributes']),axis=1)
dfAttributes

,package,name,attributes,number,partial,Results,Results2_partialDiagram,manualResults,Exact_recall,Similar_recall
0,addressbook,Electronic,"[email, website]",2,[],warranty: boolean\nbrand: String\nitemNo: int\...,"[type, brand, model, price, color, screen...",[],0.0,0.00
1,addressbook,Office,[company],1,[],state: String\nid: int\ndescription: String\nn...,"[id, name, address, phoneNumber, email, w...",[],0.0,0.00
2,addressbook,People,[name],1,[],id: int\n name: String\n surname: String,"[id, name, surname, age, gender, email, ...",[name],1.0,1.00
3,addressbook,BookVersion,[id],1,[],id: int\n title: String\n author: String\n yea...,"[pages, price, dimensions]",[],0.0,0.00
4,article,Documentation,[project],1,[],id:int\n patientId: int\n date: Date\n title: ...,"[id, title, author, date, type, document]",[document],0.0,1.00
...,...,...,...,...,...,...,...,...,...,...
206,web,Link,"[target, label]",2,[],,"[url, title, text]",[title],0.0,0.50
207,web,Version,"[name, state]",2,[],,"[id, name, date]",[name],0.5,0.50
208,web,Gallery,[label],1,[],,"[id, name, date, images]",[name],0.0,1.00
209,web,Image,"[label, src]",2,[],,"[id, title, text, url]",[title],0.0,0.50
210,web,SocialInformation,"[url, plusUrl, facebookUrl, twitterUrl]",4,['facebookUrl'],,"[facebookUrl, twitterUrl, googlePlusUrl, li...","[facebookUrl, twitterUrl, googlePlusUrl]",0.5,0.75

In [ ]:
dfAttributes.to_csv("gdrive/My Drive/NIER-ICSE/data/test/ResultsAttributesV0.csv")